spring:
  application:
    name: cex-server
  datasource:
    url: jdbc:mysql://localhost:3306/cex?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: "여기에 님 비번"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

exchange:
  symbol: "BTCKRW"

engine:
  base-url: "http://localhost:9000"
  enabled: false

logging:
  level:
    com.cex.server: DEBUG
    org.springframework.jdbc.core: DEBUG